#!/usr/bin/env python3
"""Widen the dataloader same-metro GUARD's cell table to the measured snapshot.

WHAT THIS GUARD DOES, AND WHY WIDENING IT MATTERS. `dataset/data_util.py`
carries `assert_same_metro()`, which refuses a cross-metro dataset read before
the first byte moves. It resolves both ends -- the compute cell and the `-d`
cell inside the `/cns/` path -- through `_CELL_METRO`, and it DEGRADES TO A
WARNING when either end is unlisted, deliberately, so a workstation or a new
cell is never blocked.

That degradation is correct and it is also the hole: a 21-cell table against a
fleet of 219 means the guard's usual answer is "cannot tell", printed as an
info line nobody reads, and the cross-metro read it exists to stop proceeds. So
this does not change the guard's LOGIC -- unknown still degrades -- it makes
"unknown" rare enough that the guard is doing work.

It also removes a latent dead row: `_bare_cell_of_path('/cns/nm-d/...')` returns
`'nm'`, so a `'nm-d'` KEY in this table can never be looked up. Today `'nm'` is
present too so nothing is lost, but the next such row would be a silent miss.
Storage cells are therefore emitted in BARE form, matching the lookup.

    python3 sync_guard_locality.py            # report
    python3 sync_guard_locality.py --write    # rewrite
"""
from __future__ import annotations

import argparse
import ast
import glob
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, 'cell_locality.py')
TARGETS = (os.path.expanduser('~/work/*/dataset/data_util.py'),)
EXCLUDE = re.compile(r'/(lyy-work|migrate_arms|src_snapshot|backups|archive)/')
BEGIN = '_CELL_METRO = {'

HEADER = '''# cell -> metro for the same-metro guard, MEASURED with `mach_locality -k metro`
# and regenerated by ~/work/tpu_cmd/google3_tpu_utils/sync_guard_locality.py.
# Covers BOTH compute cells (BORG_CELL) and storage cells, the latter in BARE
# form ('nm', not 'nm-d') because `_bare_cell_of_path` strips the suffix before
# looking up -- a '-d' key here can never match and is silently dead.
#
# A cell absent here still degrades the guard to a warning rather than failing
# a run, which is the right call for a workstation. The point of regenerating
# it is that "absent" should mean "genuinely new", not "nobody added it": a
# narrow table makes the guard answer "cannot tell" for most of the fleet, and
# a guard that cannot tell is a guard that is not protecting anything.
'''


def load_source():
  spec = importlib.util.spec_from_file_location('cell_locality', SOURCE)
  m = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(m)
  return m


def render(cl) -> str:
  """Rows keyed by BARE cell name; storage and compute cells merged.

  A storage cell and a compute cell can share a bare name only if they are the
  same place, so a conflict here would be a real contradiction -- assert it.
  """
  merged: dict[str, tuple[str, str]] = {}
  for cell, row in cl._MEASURED.items():  # pylint: disable=protected-access
    bare = cell[:-2] if cell.endswith('-d') else cell
    prev = merged.get(bare)
    if prev and prev[0] != row[0]:
      raise SystemExit(
          f'REFUSING: bare name {bare!r} maps to two metros '
          f'({prev[0]} and {row[0]}) -- the guard cannot key on it safely.')
    merged[bare] = (row[0], row[1])
  by_metro: dict[str, list[str]] = {}
  for bare, (metro, _) in merged.items():
    by_metro.setdefault(metro, []).append(bare)
  lines = [HEADER + BEGIN]
  for metro in sorted(by_metro):
    cont = merged[by_metro[metro][0]][1]
    lines.append(f'    # {metro} ({cont})')
    for bare in sorted(by_metro[metro]):
      lines.append(f'    {bare!r}: {metro!r},')
  lines.append('}')
  return '\n'.join(lines) + '\n'


def span_of(text: str):
  start = text.index(BEGIN)
  head = text.rfind('\n\n', 0, start)
  start = head + 2 if head != -1 else start
  return start, text.index('\n}\n', start) + len('\n}\n')


def table_in(text: str) -> dict:
  i = text.index(BEGIN)
  return ast.literal_eval(
      ast.parse(text[i + len('_CELL_METRO = '):text.index('\n}\n', i) + 2]).body[0].value)


def main() -> int:
  ap = argparse.ArgumentParser()
  ap.add_argument('--write', action='store_true')
  args = ap.parse_args()
  cl = load_source()
  if cl.self_check():
    print('REFUSING: source of truth fails self_check()', file=sys.stderr)
    return 2
  want = render(cl)
  rc = 0
  for pattern in TARGETS:
    for path in sorted(glob.glob(pattern)):
      real = os.path.realpath(path)
      if EXCLUDE.search(real + '/'):
        continue
      text = open(real).read()
      if BEGIN not in text:
        continue
      before = table_in(text)
      span = span_of(text)
      new_text = text[:span[0]] + want + text[span[1]:]
      after = table_in(new_text)
      # ZERO REGRESSION: an existing row may only vanish if it was a dead '-d'
      # key whose bare form carries the same metro.
      problems = []
      for cell, metro in before.items():
        bare = cell[:-2] if cell.endswith('-d') else cell
        got = after.get(bare)
        if got != metro:
          problems.append(f'{cell} ({metro}) -> {bare}={got}')
      if problems:
        print(f'REFUSING {real}: rows would change: {problems}')
        rc = 1
        continue
      try:
        ast.parse(new_text)
      except SyntaxError as e:
        print(f'REFUSING {real}: would not parse ({e})')
        rc = 1
        continue
      dead = [c for c in before if c.endswith('-d')]
      print(f'{"widened" if args.write else "would widen"} '
            f'{len(before)} -> {len(after)} cells  {real}'
            + (f'   (dropped dead -d keys: {dead})' if dead else ''))
      if args.write:
        tmp = real + '.tmp'
        with open(tmp, 'w') as f:
          f.write(new_text)
        os.replace(tmp, real)
  return rc


if __name__ == '__main__':
  sys.exit(main())
