load("//devtools/python/blaze:pytype.bzl", "pytype_binary")

pytype_binary(
    name = "wudump",
    srcs = ["wudump.py"],
    deps = [
        "//learning/deepmind/xmanager2/client:xmanager_api",
        "//third_party/py/absl:app",
    ],
)
